---
title: "sdcMicro"
date: "17/04/2024"
output: html_document
---

```{r packages}
    source("/home/onyxia/work/INSEE/Synthpop/Fonctions.R")
    library(synthpop)
    library(timeR)
    library(sdcMicro)
```

```{r setup, include = FALSE}
    knitr::opts_chunk$set(echo = TRUE)
```

## Dataset
```{r dataset}
    df = jeudedonnes()
    quasi = df[, c("sex", "age", "socprof", "height", "weight")]
```

## Variables
```{r variables}
"sex : factor 
age : numeric 
agegr : factor 
placesize : factor 
region : factor 
edu : factor 
eduspec : factor 
socprof : factor 
marital : factor 
ls : factor 
depress : numeric 
trust : factor 
trustfam : factor 
trustneigh : factor 
sport : factor 
nofriend : numeric 
smoke : factor 
alcabuse : factor 
alcsol : factor 
wkabint : factor 
englang : factor 
height : numeric 
weight : numeric 
bmi : numeric"
```

## Synthétisation
```{r synthetisation}
    syn_ctree = syn(quasi, method = "ctree")
```


```{r exemple}
    freq = freqCalc(df, keyVars = c(1, 2, 8, 22, 23)) # Variables quasi-identifiantes : sex, age, socprof, height, weight
    freq$fk # Fréquence d'observations égales dans l'échantillon de sous-ensemble de variables clés donné pour chaque observation.
    freq$Fk # Fréquence estimée dans la population

    indivfreq = indivRisk(freq) # Estimation du risque pour chaque observation.
    indivfreq$rk # Risque individuel

    sdc = createSdcObj(df, keyVars = c(1, 2, 8, 22, 23))
    sdc@risk$global
```

```{r local suppression}
    localS = localSupp(freq, keyVar = 2, threshold = 0.25) # Le threhold ici est élevé car le risque des observations ne dépasse ne dépassent pas 0.10 
    freq2 = freqCalc(localS$freqCalc, keyVars = c(1, 2, 8, 22, 23))
    indivfreq2 = indivRisk(freq2)
    indivfreq2$rk
```

```{r suda}
    suda = suda2(df, variables = c("sex", "age", "agegr", "placesize", "region", "edu", "eduspec", "socprof", "marital", "ls", "trust", "trustfam", "trustneigh", "sport", "smoke", "alcsol", "wkabint", "englang"))
    summary(suda)
```