---
title: "Correlations des variables"
date: "11/04/2024"
output: html_document
---

```{r packages}
    source("/home/onyxia/work/INSEE/Synthpop/Fonctions.R")
    source("http://www.sthda.com/upload/rquery_cormat.r")
    library(synthpop)
    library(timeR)
    library(corrr)
    library(corrplot)
    library(lsr)
```

```{r setup, include = FALSE}
    knitr::opts_chunk$set(echo = TRUE)
```

## Dataset
```{r dataset}
    df = jeudedonnes()
    df_num = df[, c("age", "depress", "nofriend", "height", "weight", "bmi")]
    df_fac = df[, c("sex", "agegr", "placesize", "region", "edu", "eduspec", "socprof", "marital", "ls", "trust", "trustfam", "trustneigh", "sport", "smoke", "alcsol", "wkabint", "englang")]
```

## Variables
```{r variables}
"sex : factor 
age : numeric 
agegr : factor 
placesize : factor 
region : factor 
edu : factor 
eduspec : factor 
socprof : factor 
marital : factor 
ls : factor 
depress : numeric 
trust : factor 
trustfam : factor 
trustneigh : factor 
sport : factor 
nofriend : numeric 
smoke : factor 
alcabuse : factor 
alcsol : factor 
wkabint : factor 
englang : factor 
height : numeric 
weight : numeric 
bmi : numeric"
```

## Graphiques
```{r network plot}
    x = correlate(df_num)
    network_plot(x)

    png("Graphique_correlation.png")
    rquery.cormat(df_num)
    dev.off()
```

## Correlations
```{r correlations}
    cor(df_num)
    chisq.test(df_num)
    cramersV(df_num)
    correlation(df)
```