---
title: "Analyse descriptive du jeu de données SD2011"
date: "03/04/2024"
output: html_document
---

## Packages
```{r packages}
  source("/home/onyxia/work/INSEE/Synthpop/Fonctions.R")
  library(synthpop)
  library(knitr)
  library(rmarkdown)
  library(markdown)
  library(Hmisc)
  library(ggplot2)
  library(ggcorrplot)
  library(corrr)
  library(dplyr)
  library(lsr)
  library(tidytable)
  library(lattice)
  library(tidyr)
```

## Options
```{r setup, include = FALSE}
  knitr::opts_chunk$set(echo = TRUE)
```

## Jeu de données
```{r}
  df = SD2011
```
## Description des variables
```{r variables}
"sex : Sexe (factor)
age : Age, 2011 (numeric)
agegr : Groupe d'Age, 2011 (factor)
placesize : Catégorie du lieu de résidence (factor)
region : Région (voïvodie) (factor)
edu : Diplôme d'études le plus élevé, 2011 (factor)
eduspec : Discipline de la qualification obtenue (factor)
socprof : Statut socio-économique, 2011 (factor)
unempdur : Durée totale du chômage au cours des 2 dernières années (en mois) (numeric)
income : Revenu net mensuel personnel (numeric)
marital : État civil (factor)
mmarr : Mois du mariage (numeric)
ymarr : Année du mariage (numeric)
msepdiv : Mois de séparation/divorce (numeric)
ysepdiv : Année de séparation/divorce (numeric)
ls : Perception de la vie dans son ensemble (factor)
depress : Indicateur des symptômes de dépression (numeric)
trust : Point de vue sur la confiance interpersonnelle (factor)
trustfam : Confiance aux membres de sa propre famille (factor)
trustneigh : Confiance aux voisins (factor)
sport : Participation active à une forme de sport ou d'exercice (factor)
nofriend : Nombre d'amis (numeric)
smoke : Fumeur de cigarettes (factor)
nociga : Nombre de cigarettes fumées par jour
alcabuse : Boit trop d'alcool (factor) (numeric)
alcsol : A commencer à consommer de l'alcool pour faire face aux problèmes (factor)
workab : Travaille à l'étranger en 2007-2011 (factor)
wkabdur : Temps total passé à travailler à l'étranger (character)
wkabint : Projets d'aller travailler à l'étranger dans les deux prochaines années (factor)
wkabintdur : Durée prévue du travail à l'étranger (factor)
emcc : Pays de destination prévu (factor)
englang : Connaissance de la langue anglaise (factor)
height : Taille de la personne (numeric)
weight : Poids de la personne (numeric)
bmi : Indice de masse corporelle (numeric)"
```

## Classes des variables
```{r classes}
  cat("Les classes des variables :","\n")
  for (j in 1:length(names(df))) {
    cat(names(df)[j], ":", class(df[, names(df)[j]]),"\n")
  }
```

## Description
```{r description}
  head(df)
  describe(df)
  cat("Sur les 175000 (5000*35) données,", sum(is.na(df)), "sont manquantes")
```

## NA et -8
```{r NA}
  # Affiche les variables ayant des NA
  for (k in 1:length(names(df))) {
    if (sum(is.na(df[, names(df)[k]])) > 0) {
      cat("La variable", names(df)[k], "a des NA","\n")
    }
  }

  # Affiche les variables ayant des NA codées par -8
  for (k in 1:length(names(df))) {
    temp = retirer_na(df[, names(df)[k]])
    if (sum(temp == -8) > 0) {
      cat("La variable", names(df)[k], "a des NA codés par -8","\n")
    }
  }
  # La variable income possède à la fois des NA codés par NA et par -8

  manquantes = data.frame(Categories = c("Manquantes", "Non manquantes"), Pourcentage = c(signif(100 * (sum(is.na(SD2011)) + sum(retirer_na(SD2011) == -8)) / (dim(SD2011)[1] * dim(SD2011)[2]), digits = 3), signif(100 - 100 * (sum(is.na(SD2011)) + sum(retirer_na(SD2011) == -8)) / (dim(SD2011)[1] * dim(SD2011)[2]), digits = 3)))

  png("Pourcentage_manquantes.png")
  ggplot(manquantes, aes(x = "", y = Pourcentage, fill = Categories)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  geom_text(aes(label = paste0(Pourcentage, "%")), position = position_stack(vjust = 0.5)) +
  labs(x = NULL, y = NULL) +
  theme_classic() +
  theme(axis.line = element_blank(),
          axis.text = element_blank(),
          axis.ticks = element_blank()) +
  scale_fill_brewer(palette = "Blues")
  dev.off()

  # Poucentage de NA et -8 par variables
    for (i in 1:length(df)) {
        cat("Pour la variable :", names(df)[i], "le pourcentage de NA est de :", 100 * (sum(is.na(df[names(df)[i]])) / length(df[, i])), "%", "et le pourcentage de -8 est de :", 100 * sum(retirer_na(df[names(df)[i]]) == -8)/length(df[, i]), "%", "\n")
    }
```
```

## Network Plot
```{r network plot}
  x = correlate(df)
  network_plot(x)
```

## Correlations
```{r correlations}
  correlation(df)
```

## Graphiques
```{r histogrammes}
  histogram(df$age, breaks = length(unique(df$age)))
```

## Tests
```{r test}
  spineplot(englang ~ agegr, data = SD2011, xlab = "Age group", ylab = "Knowledge of English")
  boxplot(income ~ sex, data = SD2011[SD2011$income != -8,])
```