---
title: "Métriques"
date: "16/04/2024"
output: html_document
---

## Packages
```{r packages}
    source("/home/onyxia/work/INSEE/Synthpop/Fonctions.R")
    library(synthpop)
    library(timeR)
    library(dplyr)
    library(ggplot2)
    library(reshape)
    library(GGally)
    library(moments)
    library(rcompanion)
    library(matrixcalc)
    library(readr)
    library(ggcorrplot)
    library(corrplot)
    source("http://www.sthda.com/upload/rquery_cormat.r")
```

## Options
```{r setup, include = FALSE}
    knitr::opts_chunk$set(echo = TRUE)
```

## Dataset
```{r dataset}
    df = jeudedonnes()
    df_num = df[, c("age", "depress", "nofriend", "height", "weight", "bmi")]
    df_fac = df[, c("sex", "agegr", "placesize", "region", "edu", "eduspec", "socprof", "marital", "ls", "trust", "trustfam", "trustneigh", "sport", "smoke", "alcsol", "wkabint", "englang")]
    df_numtocat = numtocat.syn(df, numtocat = "bmi", catgroups = 5, style.groups = "fisher")
    visit_sequence = c(11,16,22,2,23,24,18,19,1,17,15,21,12,13,14,20,6,3,9,4,10,8,5,7)
    regles = list(marital = "age < 18")
    regles_val = list(marital = "SINGLE")
```

## Metriques
```{r metriques}
    png("metriques.png")
    ggpairs(df_num)
    dev.off()

    sk = skewness(df_num)
    ku = kurtosis(df_num)
    mat_cov = cov(df_num)
    mat_cor = cor(df_num)
    
    liste = rep(0, length(df))
    for (i in 1:length(df)){
        mse = mean((df[, names(df)[i]] - syn_ctree$syn[, i]))
        liste[i] = mse
    }

    liste_mse = liste[c(2,11,16,22,23,24)]

    liste_vcram = vector()
    for (i in 1:length(df_fac)) { 
        for (j in 1:length(df_fac)) {
            tab_cont = table(df_fac[, names(df_fac)[i]], df_fac[, names(df_fac)[j]])
            Vcram = cramerV(tab_cont)
            liste_vcram = append(liste_vcram, as.numeric(Vcram))
        }
    }

    matrice = matrix(liste_vcram, nrow = length(df_fac), ncol = length(df_fac))
    mat_up = upper.triangle(matrice)
    vcram_dataframe = as.data.frame(mat_up, row.names = c("sex", "agegr", "placesize", "region", "edu", "eduspec", "socprof", "marital", "ls", "trust", "trustfam", "trustneigh", "sport", "smoke", "alcsol", "wkabint", "englang"), colnames = c("sex", "agegr", "placesize", "region", "edu", "eduspec", "socprof", "marital", "ls", "trust", "trustfam", "trustneigh", "sport", "smoke", "alcsol", "wkabint", "englang"))
    # vcram_triee = sort(mat_up[!(mat_up==1)]) Liste triée pour trouver les plus grandes valeurs

    # write_csv(vcram_dataframe, "/home/onyxia/work/INSEE/Synthpop/SD2011/vcramer.csv")

    coeffvar_avant = rep(0, length(df_num))
    for (i in 1:length(df_num)) {
        coeffvar_avant[i] = sd(df_num[, names(df_num)[i]]) / mean(df_num[, names(df_num)[i]])
    }

    coeffvar_apres = matrix(0, nrow = 10, ncol = length(df_num))
    for (j in 1:10) {
        syn_cart = syn(df, visit.sequence = visit_sequence, rules = regles, rvalues = regles_val, seed = j)
        syn_cart_num = syn_cart$syn[, c("age", "depress", "nofriend", "height", "weight", "bmi")]
        for (k in 1:length(syn_cart_num)) {
            coeffvar_apres[j, k] = sd(syn_cart_num[, names(syn_cart_num)[k]]) / mean(syn_cart_num[, names(syn_cart_num)[k]])
        }
    }
    colnames(coeffvar_apres) = c("age", "depress", "nofriend", "height", "weight", "bmi")
```

## Synthétisation
```{r synthetisation}
    syn_cart = syn(df, visit.sequence = visit_sequence, rules = regles, rvalues = regles_val, seed = 1)
    syn_cart_numtocat = syn(df_numtocat[[1]], visit.sequence = visit_sequence, rules = regles, rvalues = regles_val, seed = 1)
```

## pMSE
```{r propension}
    n1 = dim(df)[1]
    n2 = dim(syn_cart$syn)[1]
    N = n1 + n2
    cc = n2 / N
    maxit = 200

    df.prop = rbind(syn_cart$syn, df)
    df.prop = data.frame(df.prop, t = c(rep(1, n2), rep(0, n1)))

    logit.int = as.formula(paste("t ~ ."))
    fit = suppressWarnings(glm(logit.int, data = df.prop, family = "binomial", control = list(maxit = maxit)))
    score = predict(fit, type = "response")

    pMSE1 = (sum((score - cc)^2, na.rm = T)) / N
    # pMSE2 = utility.gen(df, syn_cart$syn, method = "logit")$pMSE

    cat("Le pMSE calculé à la main est de :", pMSE1, "\n", "Le pMSE calculé par synthpop est de :", pMSE2)
```

## Tests
```{r tests}
    row.names(mat_up) = c("sex", "agegr", "placesize", "region", "edu", "eduspec", "socprof", "marital", "ls", "trust", "trustfam", "trustneigh", "sport", "smoke", "alcsol", "wkabint", "englang")
    colnames(mat_up) = c("sex", "agegr", "placesize", "region", "edu", "eduspec", "socprof", "marital", "ls", "trust", "trustfam", "trustneigh", "sport", "smoke", "alcsol", "wkabint", "englang")
   
    rquery.cormat(mat_up)
    colnames(rquery.cormat(mat_up)) = c("sex", "agegr", "placesize", "region", "edu", "eduspec", "socprof", "marital", "ls", "trust", "trustfam", "trustneigh", "sport", "smoke", "alcsol", "wkabint", "englang")

    corrplot(mat_up, method = "circle")

    heatmap(mat_up, Rowv = NA, Colv = NA)

    vcram_melt = melt(mat_up)
    ggp = ggplot(vcram_melt, aes(X1, X2)) +
        geom_tile(aes(fill = value)) +
        scale_fill_gradient(low = "white", high = "#053061") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 18, colour = "black"),
        axis.text.y = element_text(hjust = 1, size = 18, colour = "black"),
        legend.key.size = unit(2, "cm"),
        legend.title = element_text(size = 20),
        legend.text = element_text(size = 20))
    png("Graphique_V_Cramer.png", width = 1080, height = 1080)
    ggp
    dev.off()

    rmse_cart = matrix(0, nrow = 6, ncol = 50)
    rmse_ctree = matrix(0, nrow = 6, ncol = 50)
    rmse_rf = matrix(0, nrow = 6, ncol = 50)
    rmse_para = matrix(0, nrow = 6, ncol = 50)
    for (i in 1:50) {
        syn_cart = syn(df_num, method = "cart", seed = i)
        syn_ctree = syn(df_num, method = "ctree", seed = i)
        syn_rf = syn(df_num, method = "rf", seed = i)
        syn_para = syn(df_num, method = "parametric", seed = i)
        for (j in 1:length(df_num)) {
            rmse_cart[j, i] = sqrt(mean((df_num[, names(df_num)[j]] - syn_cart$syn[, j])^2))
            rmse_ctree[j, i] = sqrt(mean((df_num[, names(df_num)[j]] - syn_ctree$syn[, j])^2))
            rmse_rf[j, i] = sqrt(mean((df_num[, names(df_num)[j]] - syn_rf$syn[, j])^2))
            rmse_para[j, i] = sqrt(mean((df_num[, names(df_num)[j]] - syn_para$syn[, j])^2))
        }
    }
    cat("Le RMSE moyen via CART est de :", mean(rmse_cart), "\n", "Le RMSE moyen via CTREE est de :", mean(rmse_ctree), "\n", "Le RMSE moyen via RF est de :", mean(rmse_rf), "\n", "Le RMSE moyen via PARA est de :", mean(rmse_para), "\n")
```

```{r graphiques}
    ptmodelavant = lm(df$height ~ df$weight)
    ptmodelapres = lm(syn_ctree$syn$height ~ syn_ctree$syn$weight)

    png("PlotTaillePoidsAvant.png", width = 1080, height = 1080)
    plot(df$weight, df$height)
    lines(df$weight, ptmodelavant$coefficients[2] * df$weight + ptmodelavant$coefficients[1], col = "red")
    dev.off()

    png("PlotTaillePoidsApres.png", width = 1080, height = 1080)
    plot(syn_ctree$syn$weight, syn_ctree$syn$height)
    lines(syn_ctree$syn$weight, ptmodelapres$coefficients[2] * syn_ctree$syn$weight + ptmodelapres$coefficients[1], col = "red")
    dev.off()

    png("BarsDepressAgegr.png", width = 1080, height = 1080)
    ggplot(df, aes(x = df$depress)) +
        geom_bar(aes(fill = df$agegr), position = "fill") +
        labs(title = "Depress coloré par Agegr", x = "Depress", y = "Pourcentage", fill = "Modalités") +
        theme(
            legend.title = element_text(colour = "black", size = 20),
            legend.text = element_text(colour = "black", size = 20),
            legend.key.size = unit(2, "cm"),
            plot.title = element_text(color = "black", size = 25, hjust = 0.5),
            axis.title.x = element_text(color = "black", size = 25, hjust = 0.5),
            axis.title.y = element_text(color = "black", size = 25, hjust = 0.5))
    dev.off()

    plot(syn_ctree$syn$weight, syn_ctree$syn$height)
    lines(syn_ctree$syn$weight, ptmodelapres$coefficients[2] * syn_ctree$syn$weight + ptmodelapres$coefficients[1], col = "red")

    bmi_avant = ggplot(df, aes(x = df$bmi, color = "red")) +
        geom_density()
    bmi_apres = ggplot(syn_cart$syn, aes(x = syn_cart$syn$bmi)) +
        geom_density() +
        ggtitle("Densités de bmi avant et après synthétisation") +
        theme(
        legend.position.inside = c(1, 1),
        legend.justification = c(1, 1),
        legend.background = element_rect(fill = "white", colour = "black"),
        plot.title = element_text(
        size = rel(1.2), lineheight = .9,
        family = "Calibri", face = "bold", colour = "black")) +
        transparent_theme
    bmi_apres_grob = ggplotGrob(bmi_apres)
    png("Densites_bmi.png", width = 1080, height = 1080)
    bmi_avant + annotation_custom(grob = bmi_apres_grob)
    dev.off()

    height_avant = ggplot(df, aes(x = df$height, color = "red")) +
        geom_density()
    height_apres = ggplot(syn_cart$syn, aes(x = syn_cart$syn$height)) +
        geom_density() +
        ggtitle("Densités de height avant et après synthétisation") +
        theme(
        legend.position.inside = c(1, 1),
        legend.justification = c(1, 1),
        legend.background = element_rect(fill = "white", colour = "black"),
        plot.title = element_text(
        size = rel(1.2), lineheight = .9,
        family = "Calibri", face = "bold", colour = "black")) +
        transparent_theme
    height_apres_grob = ggplotGrob(height_apres)
    png("Densites_height.png", width = 1080, height = 1080)
    height_avant + annotation_custom(grob = height_apres_grob)
    dev.off()

    weight_avant = ggplot(df, aes(x = df$weight, color = "red")) +
        geom_density()
    weight_apres = ggplot(syn_cart$syn, aes(x = syn_cart$syn$weight)) +
        geom_density() +
        ggtitle("Densités de weight avant et après synthétisation") +
        theme(
        legend.position.inside = c(1, 1),
        legend.justification = c(1, 1),
        legend.background = element_rect(fill = "white", colour = "black"),
        plot.title = element_text(
        size = rel(1.2), lineheight = .9,
        family = "Calibri", face = "bold", colour = "black")) +
        transparent_theme

    weight_apres_grob = ggplotGrob(weight_apres)
    png("Densites_weight.png", width = 1080, height = 1080)
    weight_avant + annotation_custom(grob = weight_apres_grob)
    dev.off()

    age_avant = ggplot(df, aes(x = df$age, color = "red")) +
        geom_density()
    age_apres = ggplot(syn_cart$syn, aes(x = syn_cart$syn$age)) +
        geom_density() +
        ggtitle("Densités de age avant et après synthétisation") +
        theme(
        legend.position.inside = c(1, 1),
        legend.justification = c(1, 1),
        legend.background = element_rect(fill = "white", colour = "black"),
        plot.title = element_text(
        size = rel(1.2), lineheight = .9,
        family = "Calibri", face = "bold", colour = "black")) +
        transparent_theme
    age_apres_grob = ggplotGrob(age_apres)
    png("Densites_age.png", width = 1080, height = 1080)
    age_avant + annotation_custom(grob = age_apres_grob)
    dev.off()

    nofriend_avant = ggplot(df, aes(x = df$nofriend, color = "red")) +
        geom_density()
    nofriend_apres = ggplot(syn_cart$syn, aes(x = syn_cart$syn$nofriend)) +
        geom_density() +
        ggtitle("Densités de nofriend avant et après synthétisation") +
        theme(
        legend.position.inside = c(1, 1),
        legend.justification = c(1, 1),
        legend.background = element_rect(fill = "white", colour = "black"),
        plot.title = element_text(
        size = rel(1.2), lineheight = .9,
        family = "Calibri", face = "bold", colour = "black")) +
        transparent_theme
    nofriend_apres_grob = ggplotGrob(nofriend_apres)
    png("Densites_nofriend.png", width = 1080, height = 1080)
    nofriend_avant + annotation_custom(grob = nofriend_apres_grob)
    dev.off()

    depress_avant = ggplot(df, aes(x = df$depress, color = "red")) +
        geom_density()
    depress_apres = ggplot(syn_cart$syn, aes(x = syn_cart$syn$depress)) +
        geom_density() +
        ggtitle("Densités de depress avant et après synthétisation") +
        theme(
        legend.position.inside = c(1, 1),
        legend.justification = c(1, 1),
        legend.background = element_rect(fill = "white", colour = "black"),
        plot.title = element_text(
        size = rel(1.2), lineheight = .9,
        family = "Calibri", face = "bold", colour = "black")) +
        transparent_theme
    depress_apres_grob = ggplotGrob(depress_apres)
    png("Densites_depress.png", width = 1080, height = 1080)
    depress_avant + annotation_custom(grob = depress_apres_grob)
    dev.off()

    png("Comparaison_age.png", width = 1080, height = 1080)
    compare(syn_cart_num, df, vars = "age", utility.stats = "pMSE")
    dev.off()

    png("Comparaison_depress.png", width = 1080, height = 1080)
    compare(syn_cart_num, df, vars = "depress", utility.stats = "pMSE")
    dev.off()

    png("Comparaison_nofriend.png", width = 1080, height = 1080)
    compare(syn_cart_num, df, vars = "nofriend", utility.stats = "pMSE")
    dev.off()

    png("Comparaison_height.png", width = 1080, height = 1080)
    compare(syn_cart_num, df, vars = "height", utility.stats = "pMSE")
    dev.off()

    png("Comparaison_weight.png", width = 1080, height = 1080)
    compare(syn_cart_num, df, vars = "weight", utility.stats = "pMSE")
    dev.off()

    png("Comparaison_bmi.png", width = 1080, height = 1080)
    compare(syn_cart_num, df, vars = "bmi", utility.stats = "pMSE")
    dev.off()

    png("PropensionBmiNofriend.png", width = 1080, height = 1080)
    ggplot(df.prop, aes(x = nofriend, y = bmi, color = score)) +
        labs(title = "Bmi en fonction de Nofriend coloré par les scores de propensions", x = "Nofriend", y = "Bmi", fill = "Scores de propension") +
        geom_point(alpha = 0.5) +
        geom_jitter() +
        scale_colour_brewer(type = "seq") +
        theme(
            legend.title = element_text(colour = "black", size = 20),
            legend.text = element_text(colour = "black", size = 20),
            legend.key.size = unit(2, "cm"),
            plot.title = element_text(color = "black", size = 25, hjust = 0.5),
            axis.title.x = element_text(color = "black", size = 25, hjust = 0.5),
            axis.title.y = element_text(color = "black", size = 25, hjust = 0.5))
    dev.off()
    
    
    breaks = c(0, 0.3, 0.4, 0.45, 0.5, 0.55, 0.6, 0.7, 1)
    labels = c("[0, 0.3[", "[0.3, 0.4[", "[0.4, 0.45[", "[0.45, 0.5[", "[0.5, 0.55[", "[0.55, 0.6[", "[0.6, 0.7[", "[0.7, 1[")
    score_cat = cut(score, breaks = breaks, labels = labels)
    png("PropensionClasseTaillePoids.png", width = 1080, height = 1080)
    ggplot(df.prop, aes(x = weight, y = height, color = score_cat)) +
        labs(title = "Height en fonction de Weight coloré par les scores de propensions", x = "Weight", y = "Height", fill = "Scores de propension") +
        geom_point(size = 5, alpha = 0.5) +
        theme_light() +
        theme(
            legend.title = element_text(colour = "black", size = 20),
            legend.text = element_text(colour = "black", size = 20),
            legend.key.size = unit(2, "cm"),
            plot.title = element_text(color = "black", size = 25, hjust = 0.5),
            axis.title.x = element_text(color = "black", size = 25, hjust = 0.5),
            axis.title.y = element_text(color = "black", size = 25, hjust = 0.5))
    dev.off()
    
    ggplot(df, aes(x = weight, y = height, colour =)) +
        labs(title = "Height en fonction de Weight sachant depress = 0", x = "Weight", y = "Height", color = "Depress") +
        geom_boxplot() +
        theme_light() +
        theme(
            legend.title = element_text(colour = "black", size = 20),
            legend.text = element_text(colour = "black", size = 20),
            legend.key.size = unit(2, "cm"),
            plot.title = element_text(color = "black", size = 20, hjust = 0.5),
            axis.title.x = element_text(color = "black", size = 20, hjust = 0.5),
            axis.title.y = element_text(color = "black", size = 20, hjust = 0.5))
```