---
title: "Analyse descriptive du jeu de données SD2011"
date: "03/04/2024"
output: html_document
---

## Packages
```{r packages}
  source("/home/onyxia/work/INSEE/SD2011/Fonctions.R")
  library(synthpop)
  library(knitr)
  library(rmarkdown)
  library(markdown)
  library(Hmisc)
  library(ggplot2)
  library(ggcorrplot)
  library(corrr)
  library(dplyr)
  library(lsr)
  library(tidytable)
  library(lattice)
  library(tidyr)
```

## Options
```{r setup, include = FALSE}
  knitr::opts_chunk$set(echo = TRUE)
```

## Jeu de données
```{r}
df = SD2011
```
## Description des variables
```{r variables}
"sex : Sexe (factor)
age : Age, 2011 (numeric)
agegr : Groupe d'Age, 2011 (factor)
placesize : Catégorie du lieu de résidence (factor)
region : Région (voïvodie) (factor)
edu : Diplôme d'études le plus élevé, 2011 (factor)
eduspec : Discipline de la qualification obtenue (factor)
socprof : Statut socio-économique, 2011 (factor)
unempdur : Durée totale du chômage au cours des 2 dernières années (en mois) (numeric)
income : Revenu net mensuel personnel (numeric)
marital : État civil (factor)
mmarr : Mois du mariage (numeric)
ymarr : Année du mariage (numeric)
msepdiv : Mois de séparation/divorce (numeric)
ysepdiv : Année de séparation/divorce (numeric)
ls : Perception de la vie dans son ensemble (factor)
depress : Indicateur des symptômes de dépression (numeric)
trust : Point de vue sur la confiance interpersonnelle (factor)
trustfam : Confiance aux membres de sa propre famille (factor)
trustneigh : Confiance aux voisins (factor)
sport : Participation active à une forme de sport ou d'exercice (factor)
nofriend : Nombre d'amis (numeric)
smoke : Fumeur de cigarettes (factor)
nociga : Nombre de cigarettes fumées par jour
alcabuse : Boit trop d'alcool (factor) (numeric)
alcsol : A commencer à consommer de l'alcool pour faire face aux problèmes (factor)
workab : Travaille à l'étranger en 2007-2011 (factor)
wkabdur : Temps total passé à travailler à l'étranger (character)
wkabint : Projets d'aller travailler à l'étranger dans les deux prochaines années (factor)
wkabintdur : Durée prévue du travail à l'étranger (factor)
emcc : Pays de destination prévu (factor)
englang : Connaissance de la langue anglaise (factor)
height : Taille de la personne (numeric)
weight : Poids de la personne (numeric)
bmi : Indice de masse corporelle (numeric)" 
```

## Description
```{r description}
  head(df)
  describe(df)
  cat("Sur les 175000 (5000*35) données,", sum(is.na(df)), "sont manquantes")
```

## NA codés par -8
```{r NA}
  cat("Les variables dont les NA sont codés par -8 sont : ", "\n")
  for (k in 1:length(names(df))){
    if (!(sum(df[, k] == -8) == 0) & (!(is.na(sum(df[, k] == -8))))) {
      cat(names(df)[k], " : ", sum((df[, k] == -8)), "\n")
    }
  }
```

## Network Plot
```{r network plot}
  x = correlate(df, corr.method = "spearman")
  network_plot(x)
```

## Correlations
```{r correlations}
  correlation(df)
```

## Graphiques
```{r histogrammes}
  histogram(df$age, breaks = length(unique(df$age)))
```

```{r}

```

## Tests
```{r test}
  variables= c(df$sex,df$age,df$agegr,df$placesize,df$region,df$edu,df$eduspec,df$socprof,df$unempdur,df$income,df$marital,df$mmarr,df$ymarr,df$msepdiv,df$ysepdiv,df$ls,df$depress,df$trust,df$trustfam,df$trustneigh,df$sport,df$nofriend,df$smoke,df$nociga,df$alcabuse,df$alcsol,df$workab,df$wkabdur,df$wkabint,df$wkabintdur,df$emcc,df$englang,df$height,df$weight,df$bmi)
  v = df$agegr

  mat = matrix(0, nrow = 3, ncol = length(levels(v)))
  mat_eff = matrix(as.numeric(mat), nrow = 3, ncol = length(levels(v)))
  for (i in 1:length(levels(v))) {
    mat_eff[1,i] = levels(v)[i]
    mat_eff[2,i] = length(which(v==levels(v)[i]))
    mat_eff[3,i] = 100 * length(which(v == levels(v)[i]))/(length(v) - sum(is.na(v)))
  }

  # Affiche la classe de chaque variable de df
  for (j in 1:length(names(df))) {
    print(class(df[, names(df)[j]]))
  }

  if (sum(is.na(variable)) > 0) {
    variable_mod = variable[!is.na(variable)]
  }
  
  df_mod = df[!is.na(df)]
  length(df_mod$income)
  income_mod = df_mod$income[complete.cases(df_mod$income), ]
```